/**
 * Persistent config for the CalDAV (Apple Reminders) backend.
 *
 * Lives in this project's own folder (caldav-server/config.json), gitignored
 * so the Apple ID and app-specific password never get committed -- same
 * placement decision as google-tasks-server/src/config.ts, made after real
 * user friction losing track of a config file tucked in the home directory.
 *
 * Unlike Google Tasks, there's no separate app-level OAuth client id/secret:
 * the app-specific password IS the whole credential, generated by the user at
 * appleid.apple.com and entered once. It's stored here the same way the
 * Google backend stores its long-lived refresh token.
 *
 * Also caches the CalDAV discovery chain (principal URL, calendar-home-set,
 * and the chosen list's collection URL) after the first successful
 * connection -- discovery is 3-4 PROPFIND round trips, and repeating it on
 * every sync would needlessly slow down and load iCloud's servers for
 * something that essentially never changes for a given account.
 */
import {join, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {mkdirSync, readFileSync, writeFileSync, existsSync} from 'node:fs';

/** Discovery results cached after the first successful connection. */
export type CalDavDiscovery = {
  /** The account's actual CalDAV server, e.g. "https://p12-caldav.icloud.com" (found via redirect from caldav.icloud.com). */
  server: string;
  principalUrl: string;
  homeSetUrl: string;
};

/** The chosen VTODO collection to sync, cached so listIncompleteTasks etc. don't need to re-resolve it by name every time. */
export type SelectedList = {
  displayName: string;
  url: string;
};

export type ServerConfig = {
  appleId?: string;
  /** App-specific password from appleid.apple.com -- NOT the user's real Apple ID password. */
  appPassword?: string;
  /** Reminder list display name to sync, matched against the plugin's list name. */
  listName: string;
  /** TCP port the HTTP server listens on. 8942 matches mac-server's default. */
  port: number;
  discovery?: CalDavDiscovery;
  selectedList?: SelectedList;
};

const PROJECT_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const CONFIG_DIR = PROJECT_ROOT;
export const CONFIG_FILE = join(CONFIG_DIR, 'config.json');

const DEFAULT_CONFIG: ServerConfig = {
  listName: 'Supernote',
  port: 8944,
};

/** Reads config, filling in defaults for any missing field. */
export function loadConfig(): ServerConfig {
  if (!existsSync(CONFIG_FILE)) return {...DEFAULT_CONFIG};
  try {
    const parsed = JSON.parse(readFileSync(CONFIG_FILE, 'utf8'));
    return {...DEFAULT_CONFIG, ...parsed};
  } catch {
    return {...DEFAULT_CONFIG};
  }
}

/** Writes config, creating the directory on first use. */
export function saveConfig(config: ServerConfig): void {
  mkdirSync(CONFIG_DIR, {recursive: true});
  writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2) + '\n', 'utf8');
}
